SELECT TOP (1000) [eid]
      ,[name]
      ,[email]
      ,[contact]
      ,[gender]
      ,[dob]
      ,[doj]
      ,[pass]
      ,[utype]
      ,[address]
      ,[salary]
  FROM [ims].[dbo].[employee]